site_name: Homeworld Mobile Unofficial Guide
site_url: https://example.com/
site_description: Homeworld Mobile Unofficial User Guide
#repo_url: https://github.com/supergnaw/homeworld-mobile-guide
nav:
#  - Intro: index.md
  - Officers: officers.md
  - Modules: modules.md
  - Systems: systems.md
#  - About: about.md
theme:
  name: mkdocs
  include_sidebar: false
#  custom_dir: custom_theme/
extra_css:
  - css/extra.css
markdown_extensions:
#  - smarty
  - toc:
      permalink: True
#  - sane_lists
